### ISSUE TITLE
setting trust settings via config to enable htmlId option

### ISSUE THREAD

**Issue by marekyggdrasil** [xu-cheng/pandoc-katex#2]
Hello, following https://github.com/KaTeX/KaTeX/issues/2003#issuecomment-843991794 would it be possible to somehow set the `trust` setting such that `htmlId` tag would be operational?

That could lead usage of macros that enable equation labels and references.

**Comment by xu-cheng** [comment]
It is now supported. Noted that we only support set `trust = true`, which trusts all user's inputs.
