### ISSUE TITLE
Matrix not rendering

### ISSUE THREAD

**Issue by jankap** [xu-cheng/pandoc-katex#3]
Trying to render a matrix via
```
$$ \begin{pmatrix}
   a & b \\
   c & d
\end{pmatrix} $$ {#eq:linearModel2}
``` 

in a markdown document. Causes 
> Error: failed to execute js (detail: undefined not callable (property 'fill' of [object Array]): JavaScript runtime error (TypeError))
Error running filter pandoc-katex:
Filter returned error status 1

Same for bmatrix or matrix. \begin{equation} works. 

Any workarounds? :)

Thanks a ton!

**Comment by xu-cheng** [comment]
Hi, I cannot reproduce your problem. Can you share the input file and cli argument you used?

**Comment by jankap** [comment]
Sorry, tried out many things and ended up with native option `--katex` of pandoc. https://pandoc.org/MANUAL.html#math-rendering-in-html 

I can try to reproduce it though.
