### ISSUE TITLE
Support for pandoc markdown's raw_tex extension

### ISSUE THREAD

**Issue by guillaumekoenig** [xu-cheng/pandoc-katex#7]
By default, pandoc markdown has [raw_tex activated](https://pandoc.org/MANUAL.html#extension-raw_tex). It allows to do things like:
```
Some test with inline math: $f(x)=x^2$. And now some raw tex:

\begin{align}
   x &= 2 \\
f(x) &= 4
\end{align}
```
The align environment in the above document is currently dropped when using pandoc-katex (but not when using eg mathjax). I think this is because in the pandoc AST it has type RawInline rather than Math. Hence pandoc-katex passes it along, and it gets dropped by pandoc during output ([doc](https://pandoc.org/MANUAL.html#extension-raw_tex) says *Inline LaTeX is ignored in output formats other than Markdown, LaTeX, Emacs Org mode, and ConTeXt.*)

I think transforming the RawInline/tex nodes into RawInline/html as is currently done for Math nodes would work. What do you think?

Note, to be complete there is RawBlock/tex as well, eg with (given in the doc):
```
\begin{tabular}{|l|l|}\hline
Age & Frequency \\ \hline
18--25  & 15 \\
26--35  & 33 \\
36--45  & 22 \\ \hline
\end{tabular}
```

**Comment by xu-cheng** [comment]
Sorry, for the late response. 

However, there is an issue that the `RawBlock` or `RawInline` can contain arbitrary tex code, which may not be supported by katex. For example, `\cite{}` command in the official document or the `tabular` environment in your comment. Passing them to katex directly would yield hard error. 

So unless there is a solution to differentiate math tex code with normal tex code, this feature is unlikely to be implemented.

**Comment by guillaumekoenig** [comment]
That's a good point. Isn't it also the case with `Math` though? For example, this document:
```
$$
\begin{tabular}{|l|l|}\hline
Age & Frequency \\ \hline
18--25  & 15 \\
26--35  & 33 \\
36--45  & 22 \\ \hline
\end{tabular}
$$
```
It produces a `Math` node, and as you pointed out it trips katex because katex doesn't know the tabular environment. As I understand, RawBlock/tex and RawInline/tex would work the same as `Math`.

**Comment by xu-cheng** [comment]
No, what you show in the example is invalid tex code even in a normal LaTeX document. So a hard error is what we should expect in this case.

RawBlock on the other hand can contain arbitrary non math tex code, and it is perfectly valid.

I will close this issue for now. Because I don't believe that pandoc's raw tex extension is intended to be used to render html file. It is likely to be designed to generate proper LaTeX pdf documents using markdown.

**Comment by guillaumekoenig** [comment]
Got it. You're right about RawBlock potentially containing arbitrary (non-math) tex code. Then I wondered: how come `pandoc --mathjax` is able to pick up the align environment from the first comment?

> So unless there is a solution to differentiate math tex code with normal tex code, this feature is unlikely to be implemented.

Turns out the pandoc HTML writer has a list of hard-coded environments to pass through: https://github.com/jgm/pandoc/blob/604d777c03ad1bd8a7f9279a255b2a693fe8c18d/src/Text/Pandoc/Writers/HTML.hs#L1687-L1725

However it seems to only work with pandoc's built-in math modes, not filters doing their own math rendering. I wonder if we could request that feature in pandoc.
