### ISSUE TITLE
Easy Fully self-contained / offline

### ISSUE THREAD

**Issue by ChrisJefferson** [xu-cheng/pandoc-katex#8]
I'm using pandoc-latex as I, and people I'm with, often have bad internet, and sometimes bad browsers (so JavaScript behaves badly).

At the moment I need to:

* Manually download the katex css

* Embed it into my pandoc to get a single html file.

This isn't that hard, but it would be nice to have a (for example) --standalone option that did that for me, and if the css was just included in pandoc-latex. I don't mind know if this is easy in a filter.

**Comment by xu-cheng** [comment]
Hi, I think this is kinda out scope of a filter. Instead, you should look up features offered by Pandoc itself to embed the css file.  As far as I am aware, it does offer several flags to embed the css like, `--css`, `--standalone`, and `--embed-resources`. For example:

```
pandoc -t html --filter pandoc-katex \
  --css "path/to/the/css" \
  --standalone --embed-resources -o output.html /path/to/input.md
```

**Comment by ChrisJefferson** [comment]
Thanks for the reply. I understand this may be too much. I'm using this options, but to be honest the other annoying thing is I'll have to make sure in future I keep my local copy of KaTeX, and pandoc-katex, in sync -- I can just fix a version of pandoc-katex I'll always use of course.
